drop table books;
create table if not exists books
(
    id     bigint generated by default as identity
        constraint books_pkey
            primary key,
    author varchar(255),
    price  double precision,
    title  varchar(255)
);

alter table books
    owner to postgres;

INSERT INTO my_db_test.public.books (author, title, price)
VALUES
    ('Достоевский Ф.М', 'Идиот', 245),
    ('Булгаков М.А.', 'Собачье сердце', 245),
    ('Кинг С.', 'Мизери', 189)
;

